// Layout of the derived campus sheet for a modern hero: the cheap presentation used on the home
// campus, hero cards and idle previews. Generated by scripts/derive-campus-heroes.ts from the
// approved elite atlas and motion sheet (no repainting; the same crop/scale/registration the
// battle renderer performs, baked once at the renderer's native 256 px frame size), stored with
// real alpha so no chroma keying happens at runtime. Battle playback never uses it.
import { heroMotionColumns } from './heroMotion';

export const CAMPUS_FRAME = 256;
export const CAMPUS_SHEET_VERSION = 1;
/** Elite poses 0–8 (idle, walk 1–6, attack 7, celebrate 8) come first, then motion idle + four
 *  stride frames facing left (row 0) and facing right (row 1). */
export interface CampusFrameMap { elite: number[]; motion: Record<number, number> }
export function campusFrameMap(key: string): CampusFrameMap {
  const columns = heroMotionColumns(key);
  const motion: Record<number, number> = {};
  const rows = [0, columns];
  let index = 9;
  for (const base of rows) for (const column of [0, 2, 3, 4, 5]) motion[base + column] = index++;
  return { elite: [0, 1, 2, 3, 4, 5, 6, 7, 8], motion };
}
export const campusFrameCount = (key: string) => 9 + Object.keys(campusFrameMap(key).motion).length;
export const campusSheetPath = (key: string) => `/assets/heroes/campus/${key}.webp`;
