import {useEffect,useState} from 'react';
import {UnitGroup,type GameState} from '../types';
import {STATIONS,FOOTBALL_PLAYS,developmentQuote,currentDevelopmentBlock,roomTier,type DevelopmentStation,type DevelopmentStep,type FootballPlay} from '../game/development';
import type {ClubAction} from '../game/authority/clubActions';
import {indoorGroupName} from '../game/indoorPlayers';
import {roomTime} from './FacilityUpgrade';
export function DevelopmentPanel({club,station,blocked,onAction,play='slants',initialUnit='ALL'}:{club:GameState;station:DevelopmentStation;blocked:boolean;onAction:(action:ClubAction)=>void;play?:FootballPlay;initialUnit?:UnitGroup|'ALL'}){
 const [stopping,setStopping]=useState(false);
 const [now,setNow]=useState(Date.now()),[unit,setUnit]=useState<UnitGroup|'ALL'>(initialUnit),[steps,setSteps]=useState<DevelopmentStep[]>([{station,play}]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(t)},[]);
 useEffect(()=>setSteps(s=>s.map(step=>step.station==='film'||step.station==='practice'?{...step,play}:step)),[play]);
 const schedule=club.development?.schedule,active=currentDevelopmentBlock(club),quote=developmentQuote(club,steps),energy=quote.reduce((n,s)=>n+s.energy,0),seconds=quote.reduce((n,s)=>n+s.seconds,0),players=club.roster.filter(p=>unit==='ALL'||p.unit===unit);
 const latest=club.development?.reports.find(r=>r.station===station&&!r.read);
 const startText:Record<DevelopmentStation,string>={weights:'Start workout',rehab:'Start rehab',film:'Study this play',practice:'Start field practice'};
 const level=club.buildings.find(b=>b.type===STATIONS[station].building)?.level??1;
 return <section className="fhq-development" aria-label={`${STATIONS[station].name} activities`}>
  {latest&&<article className="fhq-session-result" role="status"><strong>Session completed</strong><p>{latest.players.length?`${latest.players.filter(p=>p.after>p.before).length} players improved ${latest.players[0].stat}. `:''}{latest.energy?`+${latest.energy} Energy. `:''}{latest.readiness?`+${latest.readiness} readiness. `:''}{latest.station==='film'?`${FOOTBALL_PLAYS[latest.play].name} mastery is ${club.development?.mastery[latest.play]??0}/20.`:''}</p>{latest.players.slice(0,3).map(p=><span key={p.id}>{p.name} · {p.before} → <b>{p.after}</b></span>)}<button disabled={blocked} onClick={()=>onAction({type:'development.read',reportId:latest.id})}>Got it</button></article>}
  {schedule&&active?<><header><small>TEAM SCHEDULE · {schedule.completed+1}/{schedule.blocks.length}</small><h3>{STATIONS[active.station].name}</h3><p>{schedule.playerIds.length} teammates · {Math.max(0,active.finishTime-now)?roomTime((active.finishTime-now)/1000)+' remaining':'Confirming session results…'}</p></header><progress aria-label="Current session progress" max={1} value={Math.min(1,Math.max(0,(now-active.startTime)/(active.finishTime-active.startTime)))}/><ol className="fhq-schedule-list">{schedule.blocks.map((b,i)=><li key={b.id} data-state={i<schedule.completed?'done':i===schedule.completed?'active':'next'}><span>{i<schedule.completed?'✓':i+1}</span><strong>{STATIONS[b.station].name}</strong><small>{i<schedule.completed?'Completed':i===schedule.completed?'In progress':roomTime((b.finishTime-b.startTime)/1000)}</small></li>)}</ol><p className="fhq-development-note">This schedule continues while you’re away. Games and raids wait for you.</p>{stopping?<div className="fhq-stop-schedule"><p>End this schedule? The unfinished session gives no growth. Energy for later sessions is returned, up to the 100 cap.</p><button disabled={blocked} onClick={()=>{onAction({type:'development.stop',scheduleId:schedule.id});setStopping(false);}}>End schedule</button><button onClick={()=>setStopping(false)}>Keep training</button></div>:<button onClick={()=>setStopping(true)}>End schedule early…</button>}</>:<>
   <header><small>{STATIONS[station].name.toUpperCase()} · LEVEL {level}</small><h3>{station==='rehab'?'A recovery session for your team':station==='film'?'Turn film study into football IQ':station==='practice'?'Put the play on the practice field':'Build stronger players'}</h3><p>{station==='rehab'?`Restore up to ${12+4*(roomTier(level)-1)} club Energy. Foam rolling, hydration and cold plunge.`:STATIONS[station].description}{station==='film'?` · ${FOOTBALL_PLAYS[play].name} mastery ${club.development?.mastery[play]??0}/20`:''}</p></header>
   <div className="fhq-unit-choices" aria-label="Choose session group"><button aria-pressed={unit==='ALL'} onClick={()=>setUnit('ALL')}>Whole team</button>{Object.values(UnitGroup).map(u=><button key={u} aria-pressed={unit===u} onClick={()=>setUnit(u)}>{indoorGroupName[u]}</button>)}</div>
   <ol className="fhq-schedule-list" aria-label="Planned sessions">{quote.map((s,i)=><li key={i}><span>{i+1}</span><strong>{STATIONS[s.station].name}</strong><small>{roomTime(s.seconds)}</small>{steps.length>1&&<button aria-label={`Remove session ${i+1}`} onClick={()=>setSteps(v=>v.filter((_,n)=>n!==i))}>×</button>}</li>)}</ol>
   <button className="fhq-session-start" disabled={blocked||club.resources.ENERGY<energy||!players.length} onClick={()=>onAction({type:'development.start',unit,steps})}>{steps.length===1?startText[station]:'Start team schedule'} · {energy?`${energy} Energy`:'Free'}</button><p className="fhq-development-note">{players.length} players · {roomTime(seconds)} total · {energy} Energy paid now{club.resources.ENERGY<energy?' · More Energy needed':''}</p>
   <div className="fhq-append-session"><strong>Add the next stop</strong><div>{(Object.keys(STATIONS) as DevelopmentStation[]).map(s=><button key={s} disabled={steps.length>=6} onClick={()=>setSteps(v=>[...v,{station:s,play}])}>+ {STATIONS[s].name}</button>)}</div><small>Up to six sessions, in order. Your team keeps developing while you’re away.</small></div>
  </>}
 </section>;
}
