import {useEffect,useState} from 'react';
import {BuildingType,type GameState} from '../types';
import {SCOUTING_TRIPS,RECRUITING_CONTACTS,scoutingRushCost,type ScoutingTier,type RecruitingContact} from '../game/scouting';
import {unitPower} from '../battle';
import {rosterCap} from '../recruiting';
import type {ClubAction} from '../game/authority/clubActions';
import {IndoorPlayer} from './IndoorPlayer';
import {roomTime} from './FacilityUpgrade';
export function ScoutingActivities({club,blocked,onAction}:{club:GameState;blocked:boolean;onAction:(action:ClubAction)=>void}){
 const [dismiss,setDismiss]=useState<string|null>(null);
 const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(t)},[]);
 const level=club.buildings.find(b=>b.type===BuildingType.YOUTH_ACADEMY)?.level??1,scouting=club.scouting,trip=scouting?.trip,cap=rosterCap(level);
 const shortlist=<section className="fhq-prospect-shortlist" aria-label="Recruiting shortlist"><h3>Your shortlist <small>{scouting?.prospects.length??0}/6</small></h3>{!scouting?.prospects.length&&<p>Send your scout out. The report brings back an athlete you can get to know—no prospect rerolls.</p>}{scouting?.prospects.map(p=><article key={p.player.id} className="fhq-prospect-relationship"><header><IndoorPlayer unit={p.player.unit}/><div><small>{p.player.rarity} · {p.player.role} · {p.source==='agent'?'Agent network':'Scouted athlete'}</small><h4>{p.player.name}</h4><p>{unitPower(p.player)} Power · STR {p.player.stats.strength} / SPD {p.player.stats.speed} / IQ {p.player.stats.iq} · Potential {p.player.maxStat}</p></div></header><label>Interest · {p.interest}/100<progress max="100" value={p.interest}/></label>
 {p.job?<div className="fhq-recruit-contact"><strong>{RECRUITING_CONTACTS[p.job.contact].name}</strong><p>{p.job.finishTime>now?`${roomTime((p.job.finishTime-now)/1000)} remaining · +${RECRUITING_CONTACTS[p.job.contact].interest} interest`:'Confirming relationship progress…'}</p>{p.job.finishTime>now&&<button disabled={blocked||club.resources.COINS<scoutingRushCost((p.job.finishTime-now)/1000)} onClick={()=>onAction({type:'scouting.rush',playerId:p.player.id,jobId:p.job!.id})}>Finish now · {scoutingRushCost((p.job.finishTime-now)/1000)} Coins</button>}</div>:p.interest>=100?<button className="fhq-session-start" disabled={blocked||club.roster.length>=cap} onClick={()=>onAction({type:'scouting.sign',playerId:p.player.id})}>{club.roster.length>=cap?'Roster full':'Sign '+p.player.name+' · free'}</button>:<div className="fhq-contact-choices">{(Object.entries(RECRUITING_CONTACTS) as [RecruitingContact,typeof RECRUITING_CONTACTS[RecruitingContact]][]).map(([key,c])=><button key={key} disabled={blocked||p.completed.includes(key)} onClick={()=>onAction({type:'scouting.contact',playerId:p.player.id,contact:key})}><strong>{p.completed.includes(key)?'✓ ':''}{c.name}</strong><span>{p.completed.includes(key)?'Completed':`+${c.interest} interest · ${roomTime(Math.round(c.seconds/(1+(level-1)*.1)))}`}</span><small>{c.description}</small></button>)}</div>}
 {dismiss===p.player.id?<div><p>Remove this athlete and their recruiting progress? Spent Coins are not returned.</p><button disabled={blocked} onClick={()=>{onAction({type:'scouting.dismiss',playerId:p.player.id});setDismiss(null)}}>Remove prospect</button><button onClick={()=>setDismiss(null)}>Keep prospect</button></div>:<button onClick={()=>setDismiss(p.player.id)}>Pass on this prospect…</button>}
 </article>)}</section>;
 return <div className="fhq-scouting-activities">
 <header><small>BUILD YOUR RECRUITING CLASS</small><h3>Find talent. Earn their commitment.</h3><p>{club.roster.length}/{cap} roster spots · {club.resources.COINS.toLocaleString()} Coins</p></header>
 {club.recruitSlot&&<article className="fhq-session-result"><strong>{club.recruitSlot.candidate.name} · previous scouting assignment</strong><button disabled={blocked||club.recruitSlot.finishTime>now} onClick={()=>onAction({type:'recruit.sign'})}>{club.recruitSlot.finishTime<=now?'Sign this player':roomTime((club.recruitSlot.finishTime-now)/1000)+' remaining'}</button></article>}
 {!!scouting?.prospects.length&&shortlist}
 {trip?<article className="fhq-scout-trip"><small>{trip.source==='agent'?'AGENT REPORT':'SCOUT ON THE ROAD'}</small><h3>{SCOUTING_TRIPS[trip.tier].name}</h3><progress max={1} value={Math.min(1,(now-trip.startTime)/(trip.finishTime-trip.startTime))}/><p>{trip.finishTime>now?`${roomTime((trip.finishTime-now)/1000)} until your report`:'Confirming the scouting report…'}</p><small>A {SCOUTING_TRIPS[trip.tier].rarity.toLowerCase()} {trip.source==='agent'?'agent prospect, ready to sign,':'development prospect'} joins your shortlist. This trip continues while you’re away.</small></article>:<div className="fhq-scout-trips">{(Object.entries(SCOUTING_TRIPS) as [ScoutingTier,typeof SCOUTING_TRIPS[ScoutingTier]][]).map(([key,def])=><article key={key} data-locked={level<def.level}><strong>{def.name}</strong><p>{def.description}</p><span>{def.rarity} · {roomTime(def.seconds)}</span><div><button disabled={blocked||level<def.level||(scouting?.prospects.length??0)>=6} onClick={()=>onAction({type:'scouting.search',tier:key,pace:'time'})}>{level<def.level?`Scouting L${def.level}`:'Send scout · free'}</button><button disabled={blocked||level<def.level||club.resources.COINS<def.coins||(scouting?.prospects.length??0)>=6} onClick={()=>onAction({type:'scouting.search',tier:key,pace:'coins'})}>Agent report · {def.coins} Coins</button></div><small>Agent report: 15s · game-ready signing. Scout trip: more growth potential.</small></article>)}</div>}
 {!scouting?.prospects.length?shortlist:null}</div>;
}
