import './stadium.css';
import {useState} from 'react';
import {actorReadout,fieldPositionReadout,kickOutlook,downReadout} from '../game/presentation/stadiumReadouts';
import {StadiumSequence} from './StadiumSequence';
import {BuildingType,type GameState} from '../types';
import {STADIUM_OPPONENTS,footballCalls,footballRatings,FOOTBALL_ENTRY_ENERGY,coverageDescription,defensiveLookOf,isTwoPossessionGame,lookDescription,returnCoverageOf,stadiumObjective,type StadiumOpponent} from '../game/stadiumFootball';
import type {ClubAction} from '../game/authority/clubActions';
export function StadiumFootball({club,blocked,onAction}:{club:GameState;blocked:boolean;onAction:(action:ClubAction)=>void}){
 const game=club.stadiumFootball?.game,ratings=footballRatings(club),[confirmConcede,setConfirmConcede]=useState(false),[playing,setPlaying]=useState(false);
 const live=game&&!game.collected,last=game?.events.at(-1),phase=game?.phase,final=phase==='final';
 return <section className={`fhq-stadium-football${live?' fhq-football-live':''}`} aria-label="Stadium football">
 <header><small>HOME STADIUM · {game?.v===2?'TWO POSSESSIONS':'FOUR DOWNS · NO PUNTS'}</small><h3>{live?playing?'Play in motion':final?'Final whistle':game.possession==='away'?'Their possession':'Your possession':'Stadium football'}</h3></header>
 {live?<><div className="fhq-football-score"><div><small>{club.teamName}</small><strong>{playing?(game.events.at(-2)?.home??0):game.home}</strong></div><span>{final&&!playing?'FINAL':'VS'}</span><div><small>{STADIUM_OPPONENTS[game.opponent].name}</small><strong>{playing?(game.events.at(-2)?.away??0):game.away}</strong></div></div>
 <StadiumSequence onPlayback={setPlaying} game={game} level={club.buildings.find(b=>b.type===BuildingType.STADIUM)?.level??1}/>
 <div className="fhq-football-decisions" aria-busy={playing}>
 {live&&!playing&&downReadout(game)&&<p className="fhq-football-down"><strong>{downReadout(game)}</strong><span>{game.down===4?'Convert or the possession ends · No punts':(game.lineToGain===0||game.lineToGain===100)?'Goal to go · Reach the endzone':'Reach the yellow line for a new set'}</span></p>}
 {live&&!playing&&!final&&isTwoPossessionGame(game)&&<p className="fhq-football-objective" role="status"><strong>{stadiumObjective(game)}</strong></p>}
 {live&&!playing&&!final&&isTwoPossessionGame(game)&&<p className="fhq-football-context">{game.phase==='return'&&game.possession==='home'?coverageDescription(returnCoverageOf(game)):game.phase==='offense'&&game.possession==='home'?lookDescription(defensiveLookOf(game)):(game.phase==='finish'||game.v===3&&game.phase==='offense')?fieldPositionReadout(game):''}</p>}
 {last&&!playing&&<article className="fhq-football-event" role="status"><h4>{last.title}</h4><p>{last.detail}</p>{!!last.actors?.length&&<ul className="fhq-football-actors">{last.actors.filter((a,i,all)=>all.findIndex(b=>b.slot===a.slot&&b.attribute===a.attribute)===i).map(a=><li key={`${a.slot}-${a.name}`}>{actorReadout(a)}</li>)}</ul>}</article>}
 <div className="fhq-football-calls">{footballCalls(game).map(call=><button key={call.key} disabled={blocked||playing} onClick={()=>onAction({type:'stadium.call',gameId:game.id,turn:String(game.turn),call:call.key})}><strong>{call.name}</strong><small>{call.key==='field-goal'&&isTwoPossessionGame(game)?kickOutlook(game):call.detail}</small></button>)}</div>
 {final?playing?<p>Watching the final play…</p>:<div className="fhq-session-result"><strong>{game.home>game.away?'Win':game.home===game.away?'Tie':'Loss'} · {game.reward} Coins earned</strong><small>10 Energy spent at kickoff · passive recovery continues during play.</small><button className="fhq-session-start" disabled={blocked||playing} onClick={()=>onAction({type:'stadium.collect',gameId:game.id})}>Collect {game.reward} Coins</button></div>:<div className="fhq-concede">{confirmConcede?<><p>Concede this game? The 10 Energy entry is spent and there will be no rewards.</p><button disabled={blocked} onClick={()=>{onAction({type:'stadium.abandon',gameId:game.id});setConfirmConcede(false)}}>Concede game</button><button onClick={()=>setConfirmConcede(false)}>Keep playing</button></>:<><p>Call the play, then watch your team execute. Close and return to resume the next decision.</p><button onClick={()=>setConfirmConcede(true)}>Concede…</button></>}</div>}
 </div></>:<><div className="fhq-football-talent"><span>Attack <b>{ratings.attack}</b></span><span>Defense <b>{ratings.defense}</b></span><span>Readiness <b>{Math.round(ratings.readiness)}</b></span></div>{game?.collected&&<p className="fhq-session-result">Last result: {game.home}–{game.away} · {game.reward} Coins collected.</p>}<div className="fhq-football-opponents">{(Object.entries(STADIUM_OPPONENTS) as [StadiumOpponent,typeof STADIUM_OPPONENTS[StadiumOpponent]][]).map(([key,o])=><article key={key}><strong>{o.name}</strong><span>{o.power} Power · {o.style==='stack'?'Run-stopping front':o.style==='zone'?'Zone defense':'Man coverage'}</span><small>Win {o.reward} · tie {o.reward/2} · loss 20 Coins</small><button disabled={blocked||club.resources.ENERGY<FOOTBALL_ENTRY_ENERGY||!!club.development?.schedule} onClick={()=>onAction({type:'stadium.start',format:'four-downs',opponent:key})}>Kick off · {FOOTBALL_ENTRY_ENERGY} Energy</button></article>)}</div>{club.development?.schedule&&<p>Finish the team schedule before kickoff.</p>}</>}
 </section>;
}
