import {useState} from 'react';
import {StadiumSequence} from './StadiumSequence';
import {BuildingType,type GameState} from '../types';
import {STADIUM_OPPONENTS,footballCalls,footballRatings,FOOTBALL_ENTRY_ENERGY,type StadiumOpponent} from '../game/stadiumFootball';
import type {ClubAction} from '../game/authority/clubActions';
export function StadiumFootball({club,blocked,onAction}:{club:GameState;blocked:boolean;onAction:(action:ClubAction)=>void}){
 const game=club.stadiumFootball?.game,ratings=footballRatings(club),[confirmConcede,setConfirmConcede]=useState(false);
 const live=game&&!game.collected,last=game?.events.at(-1),phase=game?.phase,final=phase==='final';
 return <section className={`fhq-stadium-football${live?' fhq-football-live':''}`} aria-label="Stadium football">
 <header><small>HOME STADIUM · SHORT-FORMAT FOOTBALL</small><h3>{live?final?'Final whistle':phase==='return'||phase==='offense'||phase==='finish'||phase==='conversion'?'Your possession':'Their possession':'Two possessions. Every call counts.'}</h3><p>{live?'One possession each · equal scores finish tied.':'Kickoff, a scoring play, then a kick or conversion. Entry: 10 Energy and up to 12 readiness.'}</p></header>
 {live?<><div className="fhq-football-score"><div><small>{club.teamName}</small><strong>{game.home}</strong></div><span>{final?'FINAL':'VS'}</span><div><small>{STADIUM_OPPONENTS[game.opponent].name}</small><strong>{game.away}</strong></div></div>
 <StadiumSequence game={game} level={club.buildings.find(b=>b.type===BuildingType.STADIUM)?.level??1}/>
 <div className="fhq-football-decisions">{last&&<article className="fhq-football-event" role="status"><h4>{last.title}</h4><p>{last.detail}</p></article>}
 <div className="fhq-football-calls">{footballCalls(game).map(call=><button key={call.key} disabled={blocked} onClick={()=>onAction({type:'stadium.call',gameId:game.id,turn:String(game.turn),call:call.key})}><strong>{call.name}</strong><small>{call.detail}</small></button>)}</div>
 {final?<div className="fhq-session-result"><strong>{game.home>game.away?'Win':game.home===game.away?'Tie':'Loss'} · {game.reward} Coins earned</strong><small>10 Energy spent at kickoff · passive recovery continues during play.</small><button className="fhq-session-start" disabled={blocked} onClick={()=>onAction({type:'stadium.collect',gameId:game.id})}>Collect {game.reward} Coins</button></div>:<div className="fhq-concede">{confirmConcede?<><p>Concede this game? The 10 Energy entry is spent and there will be no rewards.</p><button disabled={blocked} onClick={()=>{onAction({type:'stadium.abandon',gameId:game.id});setConfirmConcede(false)}}>Concede game</button><button onClick={()=>setConfirmConcede(false)}>Keep playing</button></>:<><p>Close and return to resume this decision. Football never plays itself.</p><button onClick={()=>setConfirmConcede(true)}>Concede…</button></>}</div>}
 </div></>:<><div className="fhq-football-talent"><span>Attack <b>{ratings.attack}</b></span><span>Defense <b>{ratings.defense}</b></span><span>Readiness <b>{Math.round(ratings.readiness)}</b></span></div>{game?.collected&&<p className="fhq-session-result">Last result: {game.home}–{game.away} · {game.reward} Coins collected.</p>}<div className="fhq-football-opponents">{(Object.entries(STADIUM_OPPONENTS) as [StadiumOpponent,typeof STADIUM_OPPONENTS[StadiumOpponent]][]).map(([key,o])=><article key={key}><strong>{o.name}</strong><span>{o.power} Power · {o.style==='stack'?'Run-stopping front':o.style==='zone'?'Zone defense':'Man coverage'}</span><small>Win {o.reward} · tie {o.reward/2} · loss 20 Coins</small><button disabled={blocked||club.resources.ENERGY<FOOTBALL_ENTRY_ENERGY||!!club.development?.schedule} onClick={()=>onAction({type:'stadium.start',opponent:key})}>Kick off · {FOOTBALL_ENTRY_ENERGY} Energy</button></article>)}</div>{club.development?.schedule&&<p>Finish the team schedule before kickoff.</p>}</>}
 </section>;
}
