#!/usr/bin/env python3
"""Inspect alpha bounds; emit CSS placement metadata. Never modifies source art."""
import json
from pathlib import Path
from PIL import Image
root = Path(__file__).resolve().parents[1]
paths = sorted((root / 'public/assets/heroes/rig').glob('*.webp'))
paths += sorted((root / 'public/assets/heroes/franchise-rig').glob('body*.webp'))
rows = {}
for path in paths:
    with Image.open(path) as im:
        if 'A' not in im.getbands():
            continue
        box = im.getchannel('A').point(lambda value: 255 if value > 96 else 0).getbbox()
        if box:
            rows['/' + str(path.relative_to(root / 'public'))] = round((0.94 - box[3] / im.height) * 100, 4)
print('// Generated by scripts/measure-hero-feet.py; percentage of sprite canvas height.')
print('export const HERO_FOOT_OFFSET: Record<string, number> = ' + json.dumps(rows, indent=2) + ';')
